---

- name: "dobro: Install DigitalOcean droplet management tool"
  pip:
    name: "{{ doctl_dobro_name }}"
    executable: "{{ pip_executable|default(omit) }}"
  register: result
  retries: "{{ pip_install_retries }}"
  until: result is succeeded
  delay: "{{ pip_install_delay }}"

# EOF
...
