---
# tasks for vbotka.doctl

- import_tasks: vars.yml
  tags: [doctl_vars, always]

- import_tasks: debug.yml
  when: doctl_debug|bool
  tags: [doctl_debug, always]

- import_tasks: packages.yml
  when: doctl_install|bool
  tags: doctl_packages

- import_tasks: source.yml
  tags: doctl_source

- import_tasks: copy.yml
  tags: doctl_copy

- include_tasks: dobro.yml
  when: doctl_dobro|bool
  tags: doctl_dobro

# EOF
...
