---
# tasks for vbotka.doctl

- import_tasks: vars.yml
  tags: [doctl_vars, always]

- import_tasks: debug.yml
  when: doctl_debug
  tags: doctl_debug

- import_tasks: packages.yml
  tags: doctl_packages

- import_tasks: source.yml
  tags: doctl_source

- import_tasks: copy.yml
  tags: doctl_copy

- import_tasks: dobro.yml
  when: doctl_dobro
  tags: doctl_dobro

# EOF
...
