---

- debug:
    msg: "ansible_os_family [ {{ ansible_os_family }} ]"
  when: doctl_debug

# FreeBSD
- name: "packages: Install packages FreeBSD"
  pkgng:
    name: "{{ item }}"
  loop: "{{ doctl_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"
  tags: bsd_packages

- name: "packages: Install ports FreeBSD"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ doctl_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"
  tags: bsd_ports

# Debian
- name: "packages: Install packages Linux"
  package: 
    name: "{{ item }}"
  loop: "{{ doctl_packages }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")
  tags: linux_packages
        
# EOF
...
