---

- name: "packages: Debug"
  debug:
    msg: "ansible_os_family [{{ ansible_os_family }}]"
  when: doctl_debug|bool

# FreeBSD
- name: "packages: Install packages FreeBSD"
  pkgng:
    name: "{{ doctl_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install ports FreeBSD"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ doctl_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

# Linux
- name: "packages: Install packages Linux"
  package:
    name: "{{ item }}"
  loop: "{{ doctl_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ linux_install_retries }}"
  delay: "{{ linux_install_delay }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

# EOF
...
