---

- name: "vars: Set doctl_arch to {{ ansible_architecture }}"
  set_fact:
    doctl_arch: "386"
  when: ansible_architecture == "i386"

- name: "vars: Set doctl_arch to {{ ansible_architecture }}"
  set_fact:
    doctl_arch: "amd64"
  when: (ansible_architecture == "amd64") or
        (ansible_architecture == "x86_64")

- name: "vars: Fail. This play requires i386 or amd64"
  fail:
    msg: "Bailing out. This play requires i386 or amd64."
  when: doctl_arch is not defined

- name: "Default vars for {{ ansible_os_family }}
                          {{ ansible_distribution }}
                          {{ ansible_distribution_release }}"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
        - "defaults.yml"
      paths: "{{ role_path }}/vars/defaults"

- name: "Custom vars for {{ ansible_os_family }}
                         {{ ansible_distribution }}
                         {{ ansible_distribution_release }}"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
        - "defaults.yml"
      paths: "{{ role_path }}/vars"

# EOF
...
